######################## ALL FIELDS ARE REQUIRED UNLESS OTHERWISE NOTED #########################

######################################### TASK METADATA #########################################
############################ Will be displayed in the desktop node ##############################

## Task Name ##
# Maximum 24 characters.
task_name: 'CHONKUS Positivity Campaign'
author: 'ChonkusCoin'
description: "Volunteer your spare Twitter account and join our mission to break into the memecoin space! We're on a quest to bring memecoin utility to the conversation, with Chonkus. In this initiative, you'll play a crucial role in helping Chonkus get exposure in the saturated memecoin market. Please note that we only make one post per account every 24 hours. The task involves posting one (1) comment per day, which will look like: '(meme) + :egg::hatching_chick::egg:'. Before participating, please ensure that your volunteer Twitter account has passed the verification process. Rewards for this task will act as placeholders, and with the $CHONKUS token launch coming soon, participants will receive exclusive airdrops!"
repositoryUrl: 'https://github.com/tarajean13/SecretProject_Chonk'
imageUrl: 'https://bafybeifv75i7j24rfrgnswozcphl5pn3khozsyzt2a7zdqpx3sa6aamhgm.ipfs.w3s.link/Chonkus-ocean-photo.png'
infoUrl: 'https://www.koii.network/ocean/CHONKUS'

####################################### TASK CONFIGURATION ######################################

## Task Executable Network ##
# IPFS or DEVELOPMENT
# Keep this as IPFS unless you know you need to change it.
task_executable_network: "IPFS"

## Task Audit Program ##
# Task Executable Network IPFS: Path to your executable.
# Task Executable Network DEVELOPMENT: The value should be 'main'.
# Keep this as-is unless you know you need to change it.
task_audit_program: "dist/main.js"

## Round Time ##
# Duration of task, measured in slots (with each slot approximately equal to 408ms). Should be at least 800 slots.
# See https://www.koii.network/docs/concepts/what-are-tasks/what-are-tasks/gradual-consensus for more information on how round time, audit window, and submission window work.
round_time: 100000

## Audit Window ##
# The audit window should be at least 1/3 of the round time.
audit_window: 40000

## Submission Window ##
# The submission window should be at least 1/3 of the round time.
submission_window: 40000

## Minimum Stake Amount ##
# The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 1.9

## Task Bounty Type ##
# KOII or KPL
task_type: "KPL"

## Token Mint Address (ONLY for KPL tasks) ##
# The Fire Token address is provided as an example.
token_type: "7h5be74YDFFESEqLtaXFpZQERLg2156qNbQNKufFS5DA"

## Total Bounty Amount ##
# The total bounty amount that will be available for distribution over all rounds.
# Does nothing when updating a task.
total_bounty_amount: 10000

## Bounty Amount per Round ##
# The maximum amount that can be distributed per round.
# If the actual distribution per round exceeds this amount, the distribution list will fail.
bounty_amount_per_round: 100

## Allowed Failed Distributions ##
# Number of retries allowed for the distribution list if it is fails audit.
# If all retries fail, the task will not distribute anything for the round.
# This is also the number of rounds of submissions it will keep.
allowed_failed_distributions: 5

## Space ##
# Expected Task Data Size in MBs for the account size.
# Minimums: 2 for whitelisted tasks, 1 for production, 0.1 for testing.
# See https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#space for calculation details.
space: 5

## Requirement Tags (Optional) ##
# To add more global variables and task variables, please refer to the type, value, description format shown below.
requirementsTags:
  - type: TASK_VARIABLE
    value: 'TWITTER_USERNAME'
    description: 'The username of your volunteer Twitter account. Please ensure your volunteer Twitter account has passed the Twitter verification process.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PASSWORD'
    description: 'The password of your volunteer Twitter account.'
  - type: TASK_VARIABLE
    value: 'TWITTER_PHONE'
    description: 'If verification is required, will use your phone number to login.'
  - type: CPU
    value: '4-core'
  - type: RAM
    value: '5 GB'
  - type: STORAGE
    value: '5 GB'

## Tags ##
# See https://www.koii.network/docs/develop/command-line-tool/create-task-cli/create-task#tags for available tag options.
tags: ["Social Posting", "DeSci Memecoin"]

# Environment ##
# TEST or PRODUCTION
# Production mode will expose your task to all the task runners, even if not whitelisted.
environment: "PRODUCTION"

#################################### FOR UPDATING TASKS ONLY ####################################

## Old Task ID ##
task_id: ""

## Migration Description ##
migrationDescription: ""